vim.o.syntax = on
vim.o.ma = true
vim.o.mouse = a
vim.o.cursorline = true
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.softtabstop = 4
vim.o.expandtab = true
vim.o.autoread = true
vim.o.nu = true
vim.o.foldlevelstart = 99
vim.o.scrolloff = 7
vim.o.backup = false -- no backup files
vim.o.clipboard = "unnamedplus" -- allows neovim to access the system clipboard
vim.opt.completeopt = {"menuone", "noselect"} -- mostly just for cmp
vim.o.showmode = false -- we don't need to see things like -- INSERT -- anymore
vim.o.writebackup = false
vim.o.relativenumber = true
vim.opt.showtabline = 0 -- always show tabs
vim.opt.smartcase = true -- smart case
vim.opt.smartindent = true -- make indenting smarter again
vim.opt.splitbelow = true -- force all horizontal splits to go below current window
vim.opt.splitright = true -- force all vertical splits to go to the right of current window
vim.opt.swapfile = false -- creates a swapfile
vim.opt.termguicolors = true -- set term gui colors (most terminals support this)
vim.opt.undofile = true -- enable persistent undo
vim.opt.updatetime = 300 -- faster completion (4000ms default)
vim.opt.expandtab = true -- convert tabs to spaces
vim.opt.conceallevel = 0 -- so that `` is visible in markdown files

-- global configs for copilot
vim.g.copilot_filetypes = {
    ["*"] = false,
    ["javascript"] = true,
    ["typescript"] = true,
    ["lua"] = true,
    ["rust"] = true,
    ["c"] = true,
    ["c#"] = true,
    ["c++"] = true,
    ["go"] = true,
    ["python"] = true,
    ["markdown"] = true,
    ["md"] = true,
    ["html"] = true,
    ["css"] = true,
    ["java"] = true,
    ["kotlin"] = true,
    ["php"] = true,
    ["ruby"] = true,
    ["scala"] = true,
    ["svelte"] = true,
    ["swift"] = true,
    ["yaml"] = true,
    ["json"] = true,
    ["toml"] = true,
    ["ini"] = true,
    ["xml"] = true,
    ["terraform"] = true

}
